import { createCustomerService } from "./create.service";
import { getAllCustomersService } from "./getAll.service";
import { getLastCustomerIdService } from "./getLastId.service";
import { getOneCustomersService } from "./getOneById.service";
import { recoverCustomerService } from "./recover.service";
import { deleteCustomerService } from "./softDelete.service";
import { updateCustomerService } from "./update.service";
import { findByCPFCNPJService } from "./findByCPF.service";
import { directCreateCustomerService } from "./directCreate.service";
import { findByOperatorIdService } from "./findByOperatorId.service";

export const directCreate = directCreateCustomerService;
export const create = createCustomerService;
export const getAllCustomer = getAllCustomersService;
export const getOneById = getOneCustomersService;
export const recover = recoverCustomerService;
export const softDelete = deleteCustomerService;
export const update = updateCustomerService;
export const getLastId = getLastCustomerIdService;
export const findByCPFCNPJ = findByCPFCNPJService;
export const findByOperatorId = findByOperatorIdService;